#!/bin/bash

set -e

display=:10
interface=0.0.0.0

vncserver $display -depth 24 -geometry 1280x1050 -websocketPort 8443 \
  -cert /etc/ssl/certs/ssl-cert-snakeoil.pem \
  -key /etc/ssl/private/ssl-cert-snakeoil.key -sslOnly -FrameRate=24 \
  -interface $interface -httpd /usr/share/kasmvnc/www
