image: docker
services:
  - docker:dind

variables:
  DEBUG: true
  KASMVNC_COMMIT_ID: $CI_COMMIT_SHA
  GITLAB_SHARED_DIND_DIR: /builds/$CI_PROJECT_PATH/shared
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_SUBMODULE_FORCE_HTTPS: "true"
  GIT_FETCH_EXTRA_FLAGS: --tags --force
  # For example, BUILD_DISTROS_REGEX: "jammy|focal".
  # "BUILD_DISTROS_REGEX: none" won't build any distros, nor www.
  # "BUILD_DISTROS_REGEX: all" would build all distros.
  # Make sure you quote any whitespace characters you use.
  # E.g. BUILD_DISTROS_REGEX: "jammy|\ focal".
  BUILD_DISTROS_REGEX: all
  # To debug upload stage, you can limit BUILD_DISTROS_REGEX to jammy and allow
  # run_test distros to fail, by setting ALLOW_RUN_TESTS_TO_FAIL to true.
  ALLOW_RUN_TESTS_TO_FAIL: false
  DEBIAN_STABLE_IMAGE: debian:trixie-slim
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  DOCKER_AUTH_CONFIG: ${_DOCKER_AUTH_CONFIG}

workflow:
  rules:
    # Disable tag builds.
    - if: $CI_COMMIT_TAG != $CI_COMMIT_REF_NAME && $CI_PIPELINE_SOURCE != "merge_request_event"

stages:
  - www
  - build
  - functional_test
  - run_test
  - test
  - upload_build_preview

.prepare_build: &prepare_build
  - pwd
  - mkdir -p "$GITLAB_SHARED_DIND_DIR" && chmod 777 "$GITLAB_SHARED_DIND_DIR"
  - apt-get update && apt-get install -y docker.io sudo
  - echo "$DOCKER_HUB_PASSWORD" | docker login --username $DOCKER_HUB_USERNAME --password-stdin

.prepare_www: &prepare_www
  - tar -zxf output/www/kasm_www.tar.gz -C builder/
  - touch builder/www

.prepare_artfacts: &prepare_artfacts
  - cp -r builder/build/* output/
  - rm output/*.tar.gz

.enable_core_dumps: &enable_core_dumps
  - echo core > /proc/sys/kernel/core_pattern

.parallel_matrix: &parallel_matrix
  matrix:
      - DISTRO: 'ubuntu focal'
        DISTRO_SLUG: 'ubuntu_focal'
        GROUP: 0
      - DISTRO: 'ubuntu jammy'
        DISTRO_SLUG: 'ubuntu_jammy'
        GROUP: 1
      - DISTRO: 'ubuntu noble'
        DISTRO_SLUG: 'ubuntu_noble'
        GROUP: 2
      - DISTRO: 'ubuntu resolute'
        DISTRO_SLUG: 'ubuntu_resolute'
        GROUP: 3
      - DISTRO: 'debian bullseye'
        DISTRO_SLUG: 'debian_bullseye'
        GROUP: 4
      - DISTRO: 'debian bookworm'
        DISTRO_SLUG: 'debian_bookworm'
        GROUP: 5
      - DISTRO: 'debian trixie'
        DISTRO_SLUG: 'debian_trixie'
        GROUP: 6
      - DISTRO: 'kali kali-rolling'
        DISTRO_SLUG: 'kali_kali-rolling'
        GROUP: 7
      - DISTRO: 'oracle 8'
        DISTRO_SLUG: 'oracle_8'
        GROUP: 8
      - DISTRO: 'oracle 9'
        DISTRO_SLUG: 'oracle_9'
        GROUP: 9
      - DISTRO: 'opensuse 15'
        DISTRO_SLUG: 'opensuse_15'
        GROUP: 10
      - DISTRO: 'opensuse 16'
        DISTRO_SLUG: 'opensuse_16'
        GROUP: 11
      - DISTRO: 'fedora 42'
        DISTRO_SLUG: 'fedora_42'
        GROUP: 12
      - DISTRO: 'fedora 43'
        DISTRO_SLUG: 'fedora_43'
        GROUP: 13
      - DISTRO: 'alpine 321'
        DISTRO_SLUG: 'alpine_321'
        GROUP: 14
      - DISTRO: 'alpine 322'
        DISTRO_SLUG: 'alpine_322'
        GROUP: 15
      - DISTRO: 'alpine 323'
        DISTRO_SLUG: 'alpine_323'
        GROUP: 16

default:
  retry: 2
  tags:
    - oci-fixed-amd

functional_test:
  stage: functional_test
  image: $DEBIAN_STABLE_IMAGE
  tags:
    - oci-fixed-amd
  before_script:
    - *prepare_build
    - . .ci/helpers.sh
  script:
    - prepare_to_run_functional_tests
    - set +e; ./functional-test; exit_code=$?; set -e
    - upload_report_to_s3
    - put_report_into_ci_pipeline "$exit_code"
    - exit "$exit_code"
  dependencies:
    - build_amd64
  artifacts:
    paths:
      - kasmvnc-functional-tests/output/
    reports:
      junit:
        - kasmvnc-functional-tests/report/*.xml
  rules:
    # Allow functional tests to fail on feature branches.
    - if: '$CI_COMMIT_REF_NAME =~ /^feature\//'
      allow_failure: true
      when: on_success

    # Fail pipeline on all other branches, if functional tests fail.
    - when: on_success

build_www:
  stage: www
  allow_failure: false
  image: $DEBIAN_STABLE_IMAGE
  tags:
    - oci-fixed-amd
  before_script:
    - *prepare_build
  script:
    - builder/build-www
    - mkdir -p output/www
    - cd builder
    - echo $PWD
    - ls -l
    - ls -l ../output
    - tar -zcvf ../output/www/kasm_www.tar.gz www
  only:
    variables:
      - $BUILD_DISTROS_REGEX !~ /^none$/
  artifacts:
    paths:
      - output/

build_amd64:
  stage: build
  image: $DEBIAN_STABLE_IMAGE
  tags:
    - oci-fixed-amd
  before_script:
    - *prepare_build
    - *prepare_www
    - . .ci/helpers.sh
  after_script:
    - *prepare_artfacts
  script:
    - if ! is_build_this_distro "$DISTRO"; then
        exit 1;
      fi
    - builder/build-package $DISTRO
    - upload_packages $DISTRO
  artifacts:
    paths:
      - output/
  cache:
    key: "sccache-$CI_RUNNER_EXECUTABLE_ARCH-$CI_COMMIT_REF_SLUG-$DISTRO_SLUG"
    paths:
      - builder/build/.sccache
    policy: pull-push

  resource_group: "concurrent_$GROUP"
  parallel:
    *parallel_matrix
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH || $CI_COMMIT_BRANCH =~ /^release\//'
      allow_failure: false
    - allow_failure: true

build_arm64:
  stage: build
  image: $DEBIAN_STABLE_IMAGE
  tags:
    - oci-fixed-arm
  before_script:
    - *prepare_build
    - *prepare_www
    - . .ci/helpers.sh
  after_script:
    - *prepare_artfacts
  script:
    - set -e
    - if ! is_build_this_distro "$DISTRO"; then
        exit 1;
      fi
    - builder/build-package $DISTRO
    - upload_packages $DISTRO
  artifacts:
    paths:
      - output/
  cache:
    key: "sccache-$CI_RUNNER_EXECUTABLE_ARCH-$CI_COMMIT_REF_SLUG-$DISTRO_SLUG"
    paths:
      - builder/build/.sccache
    policy: pull-push
  resource_group: "concurrent_$GROUP"
  parallel:
    *parallel_matrix
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH || $CI_COMMIT_BRANCH =~ /^release\//'
      allow_failure: false
    - allow_failure: true


run_test_amd64:
  stage: run_test
  image: $DEBIAN_STABLE_IMAGE
  tags:
    - oci-fixed-amd
  before_script:
    - *prepare_build
    - *enable_core_dumps
    - . .ci/helpers.sh
  script:
    - set -e
    - is_build_this_distro "$DISTRO" && builder/test-barebones --run-test $DISTRO
  rules:
    - if: $ALLOW_RUN_TESTS_TO_FAIL == "false"
    - if: $ALLOW_RUN_TESTS_TO_FAIL == "true"
      allow_failure: true
  dependencies:
    - build_amd64
  artifacts:
    when: always
    paths:
      - run_test/core_dumps/*/core
    reports:
      junit:
        - run_test/*.xml
  parallel:
    *parallel_matrix

run_test_arm64:
  stage: run_test
  image: $DEBIAN_STABLE_IMAGE
  tags:
    - oci-fixed-arm
  before_script:
    - *prepare_build
    - *enable_core_dumps
    - . .ci/helpers.sh
  script:
    - set -e
    - is_build_this_distro "$DISTRO" && builder/test-barebones --run-test $DISTRO
  rules:
    - if: $ALLOW_RUN_TESTS_TO_FAIL == "false"
    - if: $ALLOW_RUN_TESTS_TO_FAIL == "true"
      allow_failure: true
  dependencies:
    - build_arm64
  artifacts:
    when: always
    paths:
      - run_test/core_dumps/*/core
    reports:
      junit:
        - run_test/*.xml
  parallel:
    *parallel_matrix

spec_test:
  stage: test
  image: $DEBIAN_STABLE_IMAGE
  tags:
    - kasmvnc-x86
  before_script:
    - *prepare_build
  artifacts:
    reports:
      junit:
        - SelfBench.xml
        - Benchmark.xml
  script:
    - builder/test-vncserver


make_build_preview_html:
  stage: upload_build_preview
  image: $DEBIAN_STABLE_IMAGE
  tags:
    - oci-fixed-amd
  artifacts:
    paths:
      - output/
  before_script:
    - . .ci/helpers.sh
  script:
    - prepare_to_run_scripts_and_s3_uploads
    - make_package_index_html > output/index.html
    - upload_package_index_to_build_dir_for_debugging output/index.html

upload_build_preview_html:
  stage: upload_build_preview
  needs: ["make_build_preview_html"]
  dependencies: ["make_build_preview_html"]
  image: $DEBIAN_STABLE_IMAGE
  tags:
    - oci-fixed-amd
  before_script:
    - . .ci/helpers.sh
  resource_group: upload_build_preview_html
  only:
    variables:
      - $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - prepare_to_run_scripts_and_s3_uploads
    - preview_builds_dir=kasmvnc/preview-builds
    - upload_to_s3 "output/index.html" "$preview_builds_dir/index.html" "$S3_BUCKET"
    - show_file_link_in_ci "index.html" "$UPLOADED_FILE_S3_URL"
