#!/usr/bin/env bash

set -euo pipefail

build_and_install() {
    ./autogen.sh
    ./configure --disable-shared --enable-static
    make -j$(nproc)
    make install
}

prepare_source() {
    DIR=libstatgrab
    cd /tmp
    [ -d ./${DIR} ] && rm -rf ./${DIR}
    mkdir ${DIR}

    LIBCPUID_RELEASE=$(curl -sL "https://api.github.com/repos/libstatgrab/libstatgrab/releases/latest" \
        | grep '"tag_name":' | sed -E 's/.*"tag_name": "([^"]+)".*/\1/')

    curl -Ls "https://github.com/libstatgrab/libstatgrab/archive/${LIBCPUID_RELEASE}.tar.gz" | \

    tar xzvf - -C ${DIR}/ --strip-components=1
    cd ${DIR}
}

prepare_source
build_and_install