#!/bin/bash

set -e

os=alpine
os_codename=$(cat /etc/os-release | awk '/VERSION_ID/' | grep -o '[[:digit:]]' | tr -d '\n' | head -c 3)
apkbuild_dir=/src/alpine/kasmvncserver/

cd "$apkbuild_dir" && abuild -r

[ -n "$CI" ] && sudo_cmd=sudo || sudo_cmd=
$sudo_cmd mkdir -p /src/builder/build/${os}_${os_codename}
$sudo_cmd mv \
  /src/alpine/packages/alpine/$(arch)/*.apk /src/builder/build/${os}_${os_codename}/
