#!/bin/bash

set -e

cd "$(dirname "$0")/.."

os=$(lsb_release -is | tr '[:upper:]' '[:lower:]')
os_ver=$(lsb_release -rs)
os_dir="builder/build/${os}_${os_ver}"

dpkg-buildpackage -us -uc -b
mkdir -p "$os_dir"
cp ../*.deb "$os_dir"
lintian ../*.deb
