#!/usr/bin/env bash

set -eo pipefail

update_version_to_meet_packaging_standards() {
  new_version=$(echo "$new_version" |
    sed -e 's/\([0-9]\)-\([a-zA-Z]\)/\1~\2/')
}

bump_apk() {
  builder/bump-package-version-apk "$new_version"
}


bump_rpm() {
  builder/bump-package-version-rpm "$new_version"
}

bump_deb() {
  builder/bump-package-version-deb "$new_version"
}

bump_xvnc_binary() {
  local cmd="s/#define XVNCVERSION.\+$/#define XVNCVERSION \"KasmVNC $new_version\"/"
  sed -i -e "$cmd" unix/xserver/hw/vnc/xvnc.c
}

new_version="$1"

if [[ -z "$new_version" ]]; then
  echo >&2 "Usage: $(basename "$0") <new_version>"
  exit 1
fi

cd "$(dirname "$0")/.."

update_version_to_meet_packaging_standards
bump_xvnc_binary
bump_rpm
bump_deb
bump_apk
