FROM oraclelinux:8

ENV KASMVNC_BUILD_OS oracle
ENV KASMVNC_BUILD_OS_CODENAME 8

RUN dnf install -y \
  gpg* \
  less \
  redhat-lsb-core \
  rng-tools \
  rpm* \
  rpmlint \
  tree \
  vim

COPY oracle/kasmvncserver.spec /tmp
RUN dnf builddep -y /tmp/*.spec

ENV SCRIPTS_DIR=/tmp/scripts
COPY builder/scripts $SCRIPTS_DIR

ARG OUTPUT_OWNER_UID
RUN $SCRIPTS_DIR/add-docker-user "$OUTPUT_OWNER_UID"
