FROM opensuse/leap:15.3

ENV STARTUPDIR=/dockerstartup

# base tools
RUN zypper -n install -y \
  less \
  vim \
  xterm

# deps and rpm install
RUN zypper -n install -y \
  libglvnd \
  libgomp1 \
  libjpeg8 \
  libpixman-1-0 \
  libXdmcp6 \
  libXfont2-2 \
  libxkbcommon-x11-0 \
  openssl \
  perl \
  x11-tools \
  xauth \
  xkbcomp \
  xkeyboard-config && \
  mkdir -p /etc/pki/tls/private

ARG KASMVNC_PACKAGE_DIR
COPY $KASMVNC_PACKAGE_DIR/*.rpm /tmp
RUN zypper install -y --allow-unsigned-rpm /tmp/*.rpm

RUN mkdir -p $STARTUPDIR
COPY startup/vnc_startup_barebones.sh $STARTUPDIR

RUN useradd -m foo
USER foo:kasmvnc-cert

ENTRYPOINT "/$STARTUPDIR/vnc_startup_barebones.sh"
