FROM kasmweb/ubuntu-jammy-desktop:develop

ENV KASMVNC_BUILD_OS ubuntu
ENV KASMVNC_BUILD_OS_CODENAME jammy
ENV XORG_VER 21.1.3
ENV XORG_PATCH 21
ENV DEBIAN_FRONTEND noninteractive

EXPOSE 6901

USER root

COPY builder/conf/nginx_kasm.conf /etc/nginx/conf.d/

RUN sed -i 's$# deb-src$deb-src$' /etc/apt/sources.list && \
    apt update && \
    apt install -y socat vim wget tightvncserver curl  inotify-tools sudo \
        libxfont-dev libgnutls28-dev libpng-dev libtiff-dev libgif-dev libavcodec-dev libssl-dev libxrandr-dev libxcursor-dev pkg-config libfreetype6-dev \
        libxtst-dev  xutils-dev libpixman-1-dev libxshmfence-dev libxcvt-dev libxkbfile-dev x11proto-dev libgbm-dev \
        cmake git autoconf automake libtool && \
    echo "kasm-user  ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

RUN curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
RUN apt install -y nodejs nginx
   
USER 1000

WORKDIR /src

ENTRYPOINT /bin/bash
