FROM ubuntu:18.04

RUN apt-get update && \
      apt-get -y install vim build-essential devscripts equivs

# Install build-deps for the package.
COPY ./debian/control /tmp
RUN echo YYY | mk-build-deps --install --remove /tmp/control

USER 1000
