FROM oraclelinux:9

ENV STARTUPDIR=/dockerstartup

RUN [ "$RUN_TEST" = 1 ] || dnf install -y \
  less \
  vim \
  xterm
RUN dnf config-manager --set-enabled ol9_codeready_builder
RUN dnf install -y oracle-epel-release-el9

ARG KASMVNC_PACKAGE_DIR
COPY $KASMVNC_PACKAGE_DIR/*.rpm /tmp
RUN dnf localinstall -y /tmp/*.rpm

RUN dnf install -y crypto-policies-scripts
RUN update-crypto-policies --set FIPS:SHA1

RUN mkdir -p $STARTUPDIR
COPY builder/startup/vnc_startup_barebones.sh $STARTUPDIR

RUN useradd -m foo
USER foo:kasmvnc-cert

ENTRYPOINT "/$STARTUPDIR/vnc_startup_barebones.sh"
