FROM fedora:42

ENV KASMVNC_BUILD_OS fedora
ENV KASMVNC_BUILD_OS_CODENAME 42

RUN dnf install -y fedora-packager fedora-review
RUN dnf install -y tree vim less
RUN dnf install -y dnf-plugins-core

COPY fedora/*.spec /tmp
RUN dnf builddep -y /tmp/*.spec

RUN useradd -m docker && echo "docker:docker" | chpasswd

USER docker
