ARG BASE_IMAGE
FROM $BASE_IMAGE

ENV STARTUPDIR=/dockerstartup

COPY ./builder/scripts/ /tmp/scripts/
COPY ./debian/changelog /tmp

ARG KASMVNC_PACKAGE_DIR
COPY $KASMVNC_PACKAGE_DIR/kasmvncserver_*.deb /tmp/
RUN /tmp/scripts/install_kasmvncserver_package

ARG RUN_TEST
RUN if [ "$RUN_TEST" != 1 ]; then apt-get update && apt-get -y install xterm lsb-release; fi

RUN mkdir -p $STARTUPDIR
COPY builder/startup/vnc_startup_barebones.sh $STARTUPDIR

RUN useradd -m foo && adduser foo ssl-cert
USER foo

ENTRYPOINT "/$STARTUPDIR/vnc_startup_barebones.sh"
