FROM centos:centos7

ENV STARTUPDIR=/dockerstartup

RUN yum install -y xterm
RUN yum install -y vim less
RUN yum install -y redhat-lsb-core
RUN yum install -y epel-release

ARG KASMVNC_PACKAGE_DIR
COPY $KASMVNC_PACKAGE_DIR/*.rpm /tmp/
RUN yum localinstall -y /tmp/*.rpm

RUN mkdir -p $STARTUPDIR
COPY startup/vnc_startup_barebones.sh $STARTUPDIR

RUN useradd -m foo
USER foo:kasmvnc-cert

ENTRYPOINT "/$STARTUPDIR/vnc_startup_barebones.sh"
