FROM alpine:3.21

RUN apk add shadow bash
RUN apk add abuild sudo less

ENV HOME /src/alpine
WORKDIR $HOME/kasmvncserver

ARG KASMVNC_ALPINE_PRIVATE_KEY
ARG KASMVNC_ALPINE_PUBLIC_KEY
ENV APK_KEYS_DIR=/etc/apk/keys
RUN echo -n "$KASMVNC_ALPINE_PRIVATE_KEY" > \
  $APK_KEYS_DIR/kasmvnc_signing_key.rsa
RUN echo -n "$KASMVNC_ALPINE_PUBLIC_KEY" > \
  $APK_KEYS_DIR/kasmvnc_signing_key.rsa.pub

RUN useradd -m docker && echo "docker:docker" | chpasswd

USER docker
