FROM ubuntu:resolute

ENV KASMVNC_BUILD_OS ubuntu
ENV KASMVNC_BUILD_OS_CODENAME resolute
ENV XORG_VER 21.1.22
ENV DEBIAN_FRONTEND noninteractive

RUN sed -i 's$Types: deb$Types: deb deb-src$' /etc/apt/sources.list.d/ubuntu.sources

RUN apt-get update && \
      apt-get -y install sudo

RUN apt-get update && apt-get install -y --no-install-recommends tzdata
RUN apt-get update && apt-get -y build-dep xorg-server libxfont-dev
RUN apt-get update && apt-get -y install ninja-build cmake nasm sccache git libgnutls28-dev vim wget curl
RUN apt-get update && apt-get -y install libpng-dev libtiff-dev libgif-dev libavcodec-dev libssl-dev libxrandr-dev \
    libxcursor-dev libavformat-dev libswscale-dev libva-dev libcrypt-dev

# x86_64 specific operations
RUN if [ "$(arch)" = "x86_64" ]; then \
        apt-get update && apt-get install -y intel-media-va-driver-non-free; \
    fi

RUN ARCH=$(arch) && \
  CMAKE_URL="https://github.com/Kitware/CMake/releases/download/v3.22.0/cmake-3.22.0" && \
  if [ "$ARCH" = "x86_64" ]; then \
      CMAKE_URL="${CMAKE_URL}-linux-x86_64.sh"; \
  elif [ "$ARCH" = "aarch64" ]; then \
      CMAKE_URL="${CMAKE_URL}-linux-aarch64.sh"; \
  else \
      echo "Unsupported architecture: $ARCH" && exit 1; \
  fi && \
  curl -fsSL $CMAKE_URL -o cmake.sh && \
  (echo y; echo n) | bash cmake.sh --prefix=/usr/local --skip-license && \
  rm cmake.sh

ENV SCRIPTS_DIR=/tmp/scripts
COPY builder/scripts $SCRIPTS_DIR

ARG OUTPUT_OWNER_UID
RUN $SCRIPTS_DIR/add-docker-user "$OUTPUT_OWNER_UID"

COPY --chown=$OUTPUT_OWNER_UID . /src/

ENTRYPOINT ["/src/builder/build.sh"]
