#!/bin/bash

set -e

detect_base_image() {
  BASE_IMAGE=$(echo "${os}:${os_codename}" | sed 's/\([0-9]\{2\}\)$/.\1/')
}

cd "$(dirname "$0")/.."
. ./builder/process_test_options.sh
. ./builder/common.sh
os="${1:-alpine}"
os_codename="${2:-321}"

detect_build_dir
detect_base_image
docker build --build-arg KASMVNC_PACKAGE_DIR="${build_dir}/${os}_${os_codename}" \
  --build-arg RUN_TEST="$run_test" \
  --build-arg BASE_IMAGE="$BASE_IMAGE" \
  -t kasmvnctester_barebones_${os}:$os_codename \
  -f builder/dockerfile.${os}_${os_codename}.barebones.apk.test .
echo

detect_interactive
docker run $interactive -p "443:$VNC_PORT" --rm -e "VNC_USER=foo" -e "VNC_PW=foobar" \
  -e "VNC_PORT=$VNC_PORT" \
  -e RUN_TEST="$run_test" \
  $entrypoint_executable \
  kasmvnctester_barebones_${os}:$os_codename \
  $entrypoint_args
