#!/bin/bash

set -e

cd "$(dirname "$0")/.."
. ./builder/process_test_options.sh
. ./builder/os_ver_cli.sh
. ./builder/common.sh

echo kasmvnctester_${os}:$os_codename
docker build --build-arg \
  KASMVNC_PACKAGE_DIR="builder/build/${os}_${os_codename}" \
  -t kasmvnctester_${os}:$os_codename \
  -f builder/dockerfile.${os}_${os_codename}.rpm.test .

docker run -it -p "443:$VNC_PORT" --rm \
  -e KASMVNC_VERBOSE_LOGGING=$KASMVNC_VERBOSE_LOGGING \
  -e "VNC_USER=foo" -e "VNC_PW=foobar" \
  -e "VNC_PORT=$VNC_PORT" \
  $entrypoint_executable \
  kasmvnctester_${os}:$os_codename \
  $entrypoint_args
