#!/bin/bash

set -e

cd "$(dirname "$0")"
os="${1:-debian}"
os_codename="${2:-buster}"

docker build --build-arg KASMVNC_PACKAGE_DIR="build/${os_codename}" \
  -t kasmvnctester_barebones_${os}:$os_codename \
  -f dockerfile.${os}_${os_codename}.barebones.deb.test .
echo
docker run -it -p 443:8443 --rm -e "VNC_USER=foo" -e "VNC_PW=foobar" \
  kasmvnctester_barebones_${os}:$os_codename
