#!/bin/bash

set -e

cd "$(dirname "$0")"
. ./os_ver_cli.sh

docker build --build-arg KASMVNC_PACKAGE_DIR="build/${os}_${os_ver}" \
  -t kasmvnctester_${os}:$os_ver \
  -f dockerfile.${os}${os_ver_dockerfile}.deb.test .
echo docker run -it -p 443:8443 --rm -e "VNC_USER=foo" -e "VNC_PW=bar" kasmvnctester_${os}:$os_ver
