#!/bin/bash

set -e

cd "$(dirname "$0")"
. ./os_ver_cli.sh

echo kasmvnctester_${os}:$os_codename
docker build --build-arg \
  KASMVNC_PACKAGE_DIR="build/${os}_${os_codename}" \
  -t kasmvnctester_${os}:$os_codename \
  -f dockerfile.${os}_${os_codename}.rpm.test .

docker run -it -p 443:8443 --rm \
  -e KASMVNC_VERBOSE_LOGGING=$KASMVNC_VERBOSE_LOGGING \
  -e "VNC_USER=foo" -e "VNC_PW=foobar" \
  kasmvnctester_${os}:$os_codename
